name: ashghal
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flex_color_scheme: ^8.1.1
  flutter_svg: ^2.2.3
  flutter_native_splash: ^2.4.4
  internet_connection_checker: ^3.0.0
  dartz: ^0.10.1
  http: ^1.1.2
  equatable: ^2.0.5
  shared_preferences: ^2.3.5
  geolocator: ^14.0.0
  get_it: ^9.2.0
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/

  fonts:
    - family: noto
      fonts:
        - asset: assets/fonts/NotoSansArabic-Bold.ttf
        - asset: assets/fonts/NotoSansArabic-Medium.ttf
        - asset: assets/fonts/NotoSansArabic-Regular.ttf

flutter_native_splash:
  color: "#264E36"
  image: 'assets/SCA-logo.png'
